name: CI-CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 386318839776.dkr.ecr.us-east-1.amazonaws.com/cloudshoplite

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $ECR_REGISTRY

      # 🔥 Build & Push API
      - name: Build API image
        run: |
          docker build -t api ./API
          docker tag api:latest $ECR_REGISTRY/api:latest
          docker push $ECR_REGISTRY/api:latest

      # 🔥 Build & Push Worker
      - name: Build Worker image
        run: |
          docker build -t worker ./Worker
          docker tag worker:latest $ECR_REGISTRY/worker:latest
          docker push $ECR_REGISTRY/worker:latest

      # 🔥 Build & Push Frontend
      - name: Build Frontend image
        run: |
          docker build -t frontend ./Frontend
          docker tag frontend:latest $ECR_REGISTRY/frontend:latest
          docker push $ECR_REGISTRY/frontend:latest

      # 🔧 Connect to EKS
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name cloudshoplite-cluster

      # 🚀 Deploy with Helm
      - name: Deploy using Helm
        run: |
          helm upgrade --install my-release-1 ./helm 